### ISSUE TITLE
[BUG] Axolotl crash at startup when loading many messages in once

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/axolotl#125]
I use Signal desktop a lot, and when I start Axolotl and it has to load dozens of messages, it usually crashes with `panic: concurrent write to websocket connection`.

We need to change the way messages are fetched when starting, no need to call `update active chat` for each new messages. Same thing: I'm spammed with dozens of new notifications in UT for only 2 or 3 unread conversations. 

I imagine a UX with a spinner saying "Loading your messages" and displaying them when everything is ready, with only one notification per threads, instead of per message.

```
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] SyncMessage recieved at 1587025022931 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler2             
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [axolotl] update active chat                 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler2             
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [axolotl] update active chat                 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler2             
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [axolotl] update active chat                 
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler: Message  &{+33XXXXXX receiptMessage [] <nil> 0 0 [] 1587025027329 <nil> [] [] <nil> 0 false} 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receipt: Message with timestamp 1587025027329 not found 
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler: Message  &{+33XXXXXX receiptMessage [] <nil> 0 0 [] 1587025027329 <nil> [] [] <nil> 0 false} 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] SyncMessage recieved at 1587025032717 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] handleDataMessage               
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] handleDataMessage timestamps 1587025035085 1587025035085 0 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] handleDataMessage               
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] handleDataMessage timestamps 1587025063744 1587025063744 0 
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] SyncMessage recieved at 1587025063846 
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler2             
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receipt: Message with timestamp 1587025112185 not found 
ESC[36mINFOESC[0m[2020/04/16 11:05:44] [axolotl] receiptMessageHandler2             
ESC[37mDEBUESC[0m[2020/04/16 11:05:44] [textsecure] Websocket sending message       
panic: concurrent write to websocket connection

goroutine 22 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0x3a00f3c, 0x3ae0001, 0x3ae0400, 0xd32d, 0xdc00, 0x0, 0x0)
        /gopath/path0/src/github.com/gorilla/websocket/conn.go:610 +0x5e4
github.com/gorilla/websocket.(*Conn).WriteMessage(0x2ea4240, 0x1, 0x3ae0000, 0xd72d, 0xe000, 0x0, 0x0)
        /gopath/path0/src/github.com/gorilla/websocket/conn.go:763 +0x1cc
github.com/nanu-c/axolotl/app/webserver.sendChatList(0x2ea4240)
        /gopath/path0/src/github.com/nanu-c/axolotl/app/webserver/helpers.go:32 +0x10c
github.com/nanu-c/axolotl/app/webserver.UpdateChatList()
        /gopath/path0/src/github.com/nanu-c/axolotl/app/webserver/helpers.go:285 +0x5c
github.com/nanu-c/axolotl/app/webserver.syncClients()
        /gopath/path0/src/github.com/nanu-c/axolotl/app/webserver/webserver.go:78 +0x44
created by github.com/nanu-c/axolotl/app/webserver.Run
        /gopath/path0/src/github.com/nanu-c/axolotl/app/webserver/webserver.go:32 +0x5c
```

**Comment by Flaburgan** [comment]
I didn't have any crash at startup anymore. This probably has been fixed by the work on websocket connection. Closing.
