### ISSUE TITLE
[BUG] Segfault during startup

### ISSUE THREAD

**Issue by duncan-bayne** [nanu-c/axolotl#187]
### Description

When installed as a Snap, Axolotl crashes with a segfault when run.

### Steps to Reproduce

1. Install Axolotl with `sudo snap install axolotl --candidate`.
2. Run Axoltl with `axolotl`.

**Expected behavior:** 

I expect Axoltl to launch.

**Actual behavior:**

Axoltl crashes with a segfault.

```
mobian@pinephone:~$ axolotl 
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.8.0 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Start electron                     
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
INFO[0000] astikit: starting worker...                  
DEBU[0000] [axolotl] Run Backend                        
DEBU[0000] [axolotl] openDb: /home/mobian/snap/axolotl/49/.local/share/textsecure.nanuc/db 
DEBU[0000] [axolotl] NewDataStore                       
DEBU[0000] [axoltol] axoltol-web path /snap/axolotl/49/bin/axolotl-web/ 
DEBU[0000] main: starting astilectron failed: executing failed: executing cmd failed: executer failed: starting cmd /home/mobian/snap/axolotl/49/vendor/electron-linux-arm64/electron /home/mobian/snap/axolotl/49/vendor/astilectron/main.js 127.0.0.1:39215 true --disable-dev-shm-usage --no-sandbox failed: fork/exec /home/mobian/snap/axolotl/49/vendor/electron-linux-arm64/electron: exec format error 
INFO[0000] astikit: stopping worker...                  
ERRO[0000] accept tcp 127.0.0.1:39215: use of closed network connection while TCP accepting 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72fefc]

goroutine 37 [running]:
github.com/asticode/go-astilectron.(*writer).write(0x0, 0xb95c5f, 0x11, 0xba5428, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/axolotl/parts/axolotl/go/src/github.com/asticode/go-astilectron/writer.go:39 +0x1a4
github.com/asticode/go-astilectron.synchronousEvent.func1(0x400049a080, 0xb9f00d)
        /build/axolotl/parts/axolotl/go/src/github.com/asticode/go-astilectron/helper.go:145 +0x6c
github.com/asticode/go-astilectron.synchronousFunc(0xd349c0, 0x400049a0c0, 0xd264a0, 0x40001c0000, 0x4000341700, 0xb9f00d, 0x1c, 0x42283c, 0x40003415a8, 0x4228f0, ...)
        /build/axolotl/parts/axolotl/go/src/github.com/asticode/go-astilectron/helper.go:133 +0x168
github.com/asticode/go-astilectron.synchronousEvent(0xd349c0, 0x400049a0c0, 0xd264a0, 0x40001c0000, 0x0, 0xb95c5f, 0x11, 0xba5428, 0x1, 0x0, ...)
        /build/axolotl/parts/axolotl/go/src/github.com/asticode/go-astilectron/helper.go:144 +0x9c
github.com/asticode/go-astilectron.(*Window).Create(0x40001c0000, 0xb98b79, 0x15)
        /build/axolotl/parts/axolotl/go/src/github.com/asticode/go-astilectron/window.go:304 +0x140
main.runElectron()
        /build/axolotl/parts/axolotl/go/src/github.com/nanu-c/axolotl/main.go:111 +0x36c
main.runUI(0x0, 0x0)
        /build/axolotl/parts/axolotl/go/src/github.com/nanu-c/axolotl/main.go:59 +0x88
created by main.main
        /build/axolotl/parts/axolotl/go/src/github.com/nanu-c/axolotl/main.go:140 +0xc4
```

#### Versions

```
mobian@pinephone:~$ snap info axolotl 
name:      axolotl
... snip ...
snap-id:      CYtjoLG9GyGhftUJj6ElmPHdaZdW3nAJ
tracking:     latest/candidate
refresh-date: today at 16:03 AEST
channels:
  latest/stable:    --                          
  latest/candidate: 0.8.0 2020-04-16  (49) 17MB -
  latest/beta:      ^                           
  latest/edge:      0.8.4 2020-08-14 (203) 17MB -
installed:          0.8.0             (49) 17MB -
```

#### Device

Pinephone Braveheart running Mobian nightly.

**Comment by nanu-c** [comment]
please try edge, candidate is from april, and it's an really old version. Also note, i cannot build the current version of axolotl on the snapcraft servers because of https://github.com/canonical-web-and-design/snapcraft.io/issues/3072

**Comment by Flaburgan** [comment]
The current version can now be built again, can you please try @duncan-bayne ?

**Comment by duncan-bayne** [comment]
Having installed from edge, it's still failing, but with a different error:

```
xmobian@pinephone:~$ axolotl
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.8.8 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Start electron                     
DEBU[0000] [axolotl] Run Backend                        
DEBU[0000] [axolotl] openDb: /home/mobian/snap/axolotl/234/.local/share/textsecure.nanuc/db 
INFO[0000] astikit: starting worker...                  
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axolotl] NewDataStore                       
DEBU[0000] [axoltol] axoltol-web path /snap/axolotl/234/bin/axolotl-web/ 
DEBU[0000] [axolotl] NewDataStore finished              
INFO[0000] [axolotl] Loading Chats                      
INFO[0000] [axolotl] Db setup finished                  
DEBU[0000] [axolotl] Start Session after Decryption     
DEBU[0000] [axolotl] starting Signal connection         
DEBU[0000] [axolotl] config path:  /home/mobian/snap/axolotl/234/.config/textsecure.nanuc 
DEBU[2020/10/05 15:39:01] [axoltol] Opening Dialog: getPhoneNumber     
DEBU[2020/10/05 15:39:01] [axolotl-ws] send request getPhoneNumber     
ERRO[0001] '/home/mobian/snap/axolotl/234/vendor/electron-linux-arm64/electron' exited with code: 1 
INFO[0001] astikit: stopping worker...                  
DEBU[2020/10/05 15:39:02] main: creating window failed: context canceled 
DEBU[2020/10/05 15:39:02] [axolotl-electron] open dev tools false      
INFO[0001] astikit: worker is now waiting...            
ERRO[0001] accept tcp 127.0.0.1:42497: use of closed network connection while TCP accepting 
```

**Comment by nanu-c** [comment]
can you try to do `snap install --devmode axolotl` ?

**Comment by duncan-bayne** [comment]
Trying `sudo snap install --channel=edge --devmode axolotl` installed,  but produced the following error:

```
mobian@pinephone:~$ axolotl
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.8.8 
INFO[0000] [axolotl] Setup completed                    
DEBU[0000] [axolotl] Run Backend                        
DEBU[0000] [axolotl] openDb: /home/mobian/snap/axolotl/234/.local/share/textsecure.nanuc/db 
INFO[0000] [axolotl] Start electron                     
DEBU[0000] [axolotl] NewDataStore                       
INFO[0000] astikit: starting worker...                  
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axoltol] axoltol-web path /snap/axolotl/234/bin/axolotl-web/ 
DEBU[0000] [axolotl-electron] main: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping /home/mobian/snap/axolotl/234/vendor/electron-linux-arm64-v10.1.2.zip into /home/mobian/snap/axolotl/234/vendor/electron-linux-arm64 failed: unzipping /home/mobian/snap/axolotl/234/vendor/electron-linux-arm64-v10.1.2.zip into /home/mobian/snap/axolotl/234/vendor/electron-linux-arm64 failed: astikit: opening overall zip reader on /home/mobian/snap/axolotl/234/vendor/electron-linux-arm64-v10.1.2.zip failed: zip: not a valid zip file 
INFO[0000] astikit: stopping worker...                  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71ea28]

goroutine 22 [running]:
github.com/asticode/go-astilectron.(*writer).write(0x0, 0xba71e8, 0x11, 0xbb6e4a, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /build/axolotl/parts/axolotl/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/writer.go:39 +0x1a8
github.com/asticode/go-astilectron.synchronousEvent.func1(0x40000e1a00, 0xbb0966)
        /build/axolotl/parts/axolotl/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:145 +0x6c
github.com/asticode/go-astilectron.synchronousFunc(0xd12e00, 0x40000e1a40, 0xd03960, 0x40000d4230, 0x400014d6b0, 0xbb0966, 0x1c, 0x0, 0x0, 0x41d658, ...)
        /build/axolotl/parts/axolotl/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:133 +0x168
github.com/asticode/go-astilectron.synchronousEvent(0xd12e00, 0x40000e1a40, 0xd03960, 0x40000d4230, 0x0, 0xba71e8, 0x11, 0xbb6e4a, 0x1, 0x0, ...)
        /build/axolotl/parts/axolotl/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:144 +0x9c
github.com/asticode/go-astilectron.(*Window).Create(0x40000d4230, 0x4000118560, 0x15)
        /build/axolotl/parts/axolotl/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/window.go:306 +0x140
main.runElectron()
        /build/axolotl/parts/axolotl/build/main.go:111 +0x3e0
main.runUI(0x0, 0x0)
        /build/axolotl/parts/axolotl/build/main.go:61 +0x88
created by main.main
        /build/axolotl/parts/axolotl/build/main.go:141 +0xe4
```

**Comment by nanu-c** [comment]
Okey and which mobian do you use? The pmos or debian or manjaro? actually we shouldn't use electron on pinephone, this a waste of resources. Can you check if qmlscene is installed?

**Comment by joshbowyer** [comment]
Just to clarify the above question: mobian is just mobile+debian. Mobian/PMOS/Manjaro all use Phosh.

Also, this issue should be solved once the `qt` mode is made available as a snap, OR if the user installs the `qt` mode via flatpak.

**Comment by olof-nord** [comment]
This was a bit tricky. I just ran into this, and there seems to be a new dependency introduced by the electron project.

On arch, the solution was to run `paru gconf`.

On Ubuntu, the issue below lists `apt-get install libgconf-2-4` as a possible solution.

https://github.com/electron/electron/issues/1518

**Comment by olof-nord** [comment]
This issue seems to be similar to https://github.com/nanu-c/axolotl/issues/433.

**Comment by Id2ndR** [comment]
It seems that the 1.0.0 release use the web version and deprecated qt one. Maybe this issue can be close?
