### ISSUE TITLE
[BUG] electron startup fails: not a valid zip file

### ISSUE THREAD

**Issue by langfingaz** [nanu-c/axolotl#267]
### Description

I tried the [installation with flatpak](https://github.com/nanu-c/axolotl/blob/main/docs/INSTALL.md#flatpak) on my PinePhone.

When I run the application it fails to load electron with an error that `/home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64-v10.1.2.zip` is not a valid zip file. 

`stat /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64-v10.1.2.zip` reveals that the file is 0 bytes in size!

This issue is probably related to https://github.com/nanu-c/axolotl/issues/64#issuecomment-624580040

### Steps to Reproduce

**Note**: I'm not sure if this is repoducable. What I did so far:

1. Follow [flatpak installation instructions](https://github.com/nanu-c/axolotl/blob/main/docs/INSTALL.md#flatpak)
2. Start with `flatpak run org.nanuc.Axolotl`

**Expected behavior:** App should startup without errors ;)

**Actual behavior:**

<details>
<summary>App exits with following error message:</summary>

```
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.8.9 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Start electron                     
DEBU[0000] [axolotl] Run Backend                        
INFO[0000] astikit: starting worker...                  
DEBU[0000] [axolotl] openDb: /home/alarm/.local/share/textsecure.nanuc/db 
DEBU[0000] [axolotl] NewDataStore                       
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axolotl] Using axolotl-web path /app/bin/axolotl-web/dist 
DEBU[0000] [axolotl] NewDataStore finished              
INFO[0000] [axolotl] Loading Chats                      
DEBU[0000] [axolotl-electron] main: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64-v10.1.2.zip into /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64 failed: unzipping /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64-v10.1.2.zip into /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64 failed: astikit: opening overall zip reader on /home/alarm/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64-v10.1.2.zip failed: zip: not a valid zip file 
INFO[0000] [axolotl] Db setup finished                  
DEBU[0000] [axolotl] Start Session after Decryption     
DEBU[0000] [axolotl] starting Signal connection         
DEBU[0000] [axolotl] config path:  /home/alarm/.config/textsecure.nanuc 
DEBU[2020/11/22 12:47:29] [axoltol] Opening Dialog: getPhoneNumber     
DEBU[2020/11/22 12:47:29] [axolotl-ws] send request getPhoneNumber     
INFO[0000] astikit: stopping worker...                  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72c96c]

goroutine 39 [running]:
github.com/asticode/go-astilectron.(*writer).write(0x0, 0xbde1f0, 0x11, 0xbee0c4, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/writer.go:39 +0x1a4
github.com/asticode/go-astilectron.synchronousEvent.func1(0x40005b0000, 0xbe7adb)
	/root/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:145 +0x6c
github.com/asticode/go-astilectron.synchronousFunc(0xd80500, 0x40005b0040, 0xd70a60, 0x40000940a0, 0x40004f96b0, 0xbe7adb, 0x1c, 0x0, 0x0, 0x419780, ...)
	/root/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:133 +0x168
github.com/asticode/go-astilectron.synchronousEvent(0xd80500, 0x40005b0040, 0xd70a60, 0x40000940a0, 0x0, 0xbde1f0, 0x11, 0xbee0c4, 0x1, 0x0, ...)
	/root/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/helper.go:144 +0x9c
github.com/asticode/go-astilectron.(*Window).Create(0x40000940a0, 0x4000038c20, 0x15)
	/root/go/pkg/mod/github.com/asticode/go-astilectron@v0.17.0/window.go:306 +0x140
main.runElectron()
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:112 +0x3e0
main.runUI(0x0, 0x0)
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:62 +0x88
created by main.main
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:142 +0xe4
```

</details>

#### Versions

`main` branch, last commit: https://github.com/nanu-c/axolotl/commit/5b4ed8c9bcc04d6c756cc12788927d9a645a61a5

#### Device

PinePhone (aarch64) running [Arch Linux ARM](https://github.com/dreemurrs-embedded/Pine64-Arch/releases/tag/20201112)

**Comment by joshbowyer** [comment]
Actually this is related to https://github.com/nanu-c/axolotl/issues/253

**Comment by joshbowyer** [comment]
For standalone installation, this is solved by the addition of the `qt` version.

**Comment by nanu-c** [comment]
if you have a similar problem again, please open a new issue.
