### ISSUE TITLE
[BUG] Axolotl crashes on message send using qml branch

### ISSUE THREAD

**Issue by Undef-a** [nanu-c/axolotl#276]
### Description
Using https://github.com/nanu-c/axolotl/pull/273 (I am unable to test without this change) axolotl crashes when sending a message. 

### Steps to Reproduce

1. Start Axolotl
2. Create a contact
3. Attempt to send a message to contact. 

**Expected behavior:** [What you expect to happen]
Message is sent. 
**Actual behavior:** [What actually happens]
Frontend: nothing.
Backend: Crashes with the following output: 
```
?2004l36mINFO0m[0000] [axolotl] Starting Signal for Ubuntu version 0.8.9
36mINFO0m[0000] [axolotl] Setup completed
36mINFO0m[0000] [axolotl] Axolotl-gui starting for sys: qml
36mINFO0m[0000] [axolotl] Axolotl server started
36mINFO0m[0000] [axolotl] Starting axolotl ws
37mDEBU0m[0000] [axolotl] Run Backend
37mDEBU0m[0000] [axolotl] openDb: /home/mobian/.local/share/textsecure.nanuc/db
37mDEBU0m[0000] [axolotl] Using axolotl-web path /app/bin/axolotl-web/dist
37mDEBU0m[0000] [axolotl] NewDataStore
37mDEBU0m[0000] [axolotl] NewDataStore finished
36mINFO0m[0000] [axolotl] Loading Chats
36mINFO0m[0000] [axolotl] Db setup finished
37mDEBU0m[0000] [axolotl] Start Session after Decryption
37mDEBU0m[0000] [axolotl] starting Signal connection
37mDEBU0m[0000] [axolotl] config path:  /home/mobian/.config/textsecure.nanuc
36mINFO0m[2020/12/06 09:15:24] [axolotl] Registered
37mDEBU0m[2020/12/06 09:15:24] [axolotl-ws] send request registrationDone
37mDEBU0m[2020/12/06 09:15:25] [textsecure] PUT /v1/directory/tokens 200
37mDEBU0m[2020/12/06 09:15:25] [axolotl] refresh contacts 1
37mDEBU0m[2020/12/06 09:15:25] [textsecure] Websocket Connecting to signal-server
[10:21:1206/091526.061360:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Address already in use (98)
file:///home/mobian/guis/qml/qml/MainQML.qml:26: TypeError: Cannot read property 'bottom' of null
file:///home/mobian/guis/qml/qml/MainQML.qml:25: TypeError: Cannot read property 'right' of null
file:///home/mobian/guis/qml/qml/MainQML.qml:24: TypeError: Cannot read property 'top' of null
file:///home/mobian/guis/qml/qml/MainQML.qml:23: TypeError: Cannot read property 'left' of null
[10:29:1206/091526.521596:ERROR:gles2_cmd_decoder.cc(2843)] [GroupMarkerNotSet(crbug.com/242999)!:2895084C7F000000]GL ERROR :GL_INVALID_ENUM : BackFramebuffer::Create: <- error from previous GL command
[10:29:1206/091526.598089:ERROR:gles2_cmd_decoder.cc(2843)] [GroupMarkerNotSet(crbug.com/242999)!:68A7164C7F000000]GL ERROR :GL_INVALID_ENUM : BackFramebuffer::Create: <- error from previous GL command
[10:29:1206/091526.692857:ERROR:gles2_cmd_decoder.cc(2843)] [GroupMarkerNotSet(crbug.com/242999)!:58D2184C7F000000]GL ERROR :GL_INVALID_ENUM : BackFramebuffer::Create: <- error from previous GL command
37mDEBU0m[2020/12/06 09:15:27] [textsecure] Websocket Connected successfully
37mDEBU0m[2020/12/06 09:15:27] verb:"PUT" path:"/api/v1/queue/empty" headers:"X-Signal-Timestamp:4567646846465" id:xxxxxxxxxxxxxxxxxxx
36mINFO0m[2020/12/06 09:15:27] [textsecure] No new messages
37mDEBU0m[2020/12/06 09:15:27] [textsecure] Websocket sending message
36mINFO0m[2020/12/06 09:15:29] [axolotl] Client Connected true
37mDEBU0m[2020/12/06 09:15:29] [axolotl] send darkmode to client false
37mDEBU0m[2020/12/06 09:15:29] [axolotl-ws] getRegistrationStatus
37mDEBU0m[2020/12/06 09:15:29] [axolotl-ws] send request registrationDone
36mINFO0m[2020/12/06 09:15:29] websocket: close 1001 (going away)
36mINFO0m[2020/12/06 09:15:31] [axolotl] Client Connected true
37mDEBU0m[2020/12/06 09:15:31] [axolotl] send darkmode to client false
37mDEBU0m[2020/12/06 09:15:31] [axolotl-ws] getRegistrationStatus
37mDEBU0m[2020/12/06 09:15:31] [axolotl-ws] send request registrationDone
31mERRO0m[2020/12/06 09:15:31] [axolotl-ws] send message websocket: close sent
37mDEBU0m[2020/12/06 09:15:31] [axolotl-ws] remove client
qml: [Axolotl Web View] [JS] (http://localhost:9080/js/chunk-vendors.f7e98d0b.js:29) No translations found for en-AU
36mINFO0m[2020/12/06 09:15:35] [axolotl] Create chat for  +82937282900738
qml: [Axolotl Web View] [JS] (http://localhost:9080/js/chunk-vendors.f7e98d0b.js:29) No translations found for en-AU
36mINFO0m[2020/12/06 09:15:35] [axolotl] Open chat with id:  1
37mDEBU0m[2020/12/06 09:15:35] [axolotl] Enter chat  +82937282900738
31mERRO0m[2020/12/06 09:15:35] [axolotl] get messagelist missing destination name quotedId in *[]*store.Message
missing destination name quotedId in *[]*store.Message
37mDEBU0m[2020/12/06 09:15:40] [axolotl] send message to  +82937282900738
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x968ec0]

goroutine 108 [running]:
github.com/nanu-c/axolotl/app/webserver.MessageHandler(0x0)
        /run/build/axolotl/src/github.com/Undef-a/axolotl/app/webserver/handler.go:35 +0x48
created by github.com/nanu-c/axolotl/app/webserver.wsReader
        /run/build/axolotl/src/github.com/Undef-a/axolotl/app/webserver/webserver.go:178 +0x1198
?2004h0;mobian@mobian: ~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin01;32mmobian@mobian00m:01;34m~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin00m$ KAA0;mobian@mobian: ~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin01;32mmobian@mobian00m:01;34m~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin00m$ KAA0;mobian@mobian: ~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin01;32mmobian@mobian00m:01;34m~/.local/share/flatpak/app/org.nanuc.Axolotl/aarch64/main/active/files/bin00m$ exit
```
#### Versions

0.8.9 with qml patch. 

#### Device
Pinephone.

**Comment by nanu-c** [comment]
You need this patch: https://github.com/nanu-c/axolotl/pull/272/files and then either re-register or use dbbrowser for sql to rename the column in the messages table `quotedId` to `quoteId`. It was a typo

**Comment by Undef-a** [comment]
Confirmed. This issue is resolved by that PR.
