### ISSUE TITLE
[BUG] Unable to accept groupV2 invitations with Signal Desktop

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/axolotl#547]
### Description

I try to join a group I was invited to.
Axolotl is missing support to accept an invitation so I try it using Signal Desktop.
The person who invited me exchanged messages with me before inviting me, in order to make sure that my actual profile key is used.
Clicking on "accept" I get an error message that something went wrong.
The log (see below) suggests that my profile doesn't have a profileKeyCredential.
Link to the Signal Desktop Code, throwing that error: https://github.com/signalapp/Signal-Desktop/blob/017a0fa80701add7fb51d6a33082db41d3f6c65b/ts/models/conversations.ts#L441

### Steps to Reproduce

1. Link with Signal Desktop 
2. Exchange messanges with someone
3. Get invited into a group by that user
4. Click "Accept" in Signal Desktop

**Expected behavior:**
I'm promoted to be a member of that group

**Actual behavior:**
I get an error message that something went wrong.

#### Versions

Axolotl 1.0.1.1
Signal Desktop 5.14.0

#### Device
Volla Phone
Linux Mint

#### Debug Log
The relevant part of the Signal Desktop log:
``` log
INFO  2021-08-22T19:31:28.562Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]4ca
INFO  2021-08-22T19:31:28.667Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]4ca 200 Success
INFO  2021-08-22T19:31:28.668Z Setting sealedSender to DISABLED for conversation [REDACTED]4ca ([REDACTED]122)
INFO  2021-08-22T19:31:28.668Z Conversation job modifyGroupV2 took 107ms
ERROR 2021-08-22T19:31:28.669Z modifyGroupV2/promotePendingMember/groupv2([REDACTED]DQ4=): Error updating: Error: promotePendingMember/groupv2([REDACTED]DQ4=): No profileKeyCredential for conversation [REDACTED]4ca ([REDACTED]122)
    at ConversationModel.promotePendingMember ([REDACTED]/resources/app.asar/preload.bundle.js:2:5437623)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5273287
ERROR 2021-08-22T19:31:28.669Z longRunningTaskWrapper/onAccept/groupv2([REDACTED]DQ4=): Error! Error: promotePendingMember/groupv2([REDACTED]DQ4=): No profileKeyCredential for conversation [REDACTED]4ca ([REDACTED]122)
    at ConversationModel.promotePendingMember ([REDACTED]/resources/app.asar/preload.bundle.js:2:5437623)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5273287
INFO  2021-08-22T19:31:28.669Z longRunningTaskWrapper/onAccept/groupv2([REDACTED]DQ4=): Showing error dialog
ERROR 2021-08-22T19:31:28.683Z Top-level unhandled promise rejection: Error: promotePendingMember/groupv2([REDACTED]DQ4=): No profileKeyCredential for conversation [REDACTED]4ca ([REDACTED]122)
    at ConversationModel.promotePendingMember ([REDACTED]/resources/app.asar/preload.bundle.js:2:5437623)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5273287
```

**Comment by Danfro** [comment]
I actually managed to join a v2 group. But I only did that once and I do not recall the steps I took to succeed.

**Comment by Blackoverflow** [comment]
I think this may be related:
I tried to change my profile in Signal Desktop and got an error message.
The related log is:
```
INFO  2021-08-22T20:46:22.056Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]4ca
INFO  2021-08-22T20:46:22.164Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]4ca 200 Success
INFO  2021-08-22T20:46:22.164Z Setting sealedSender to DISABLED for conversation [REDACTED]4ca ([REDACTED]122)
ERROR 2021-08-22T20:46:22.166Z assert failure: Error: profileKey
    at Object.assert ([REDACTED]/resources/app.asar/preload.bundle.js:2:7142921)
    at Object.encryptProfileData ([REDACTED]/resources/app.asar/preload.bundle.js:2:7165421)
    at Object.writeProfile ([REDACTED]/resources/app.asar/preload.bundle.js:2:6464336)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:6652270
ERROR 2021-08-22T20:46:22.168Z myProfileChanged TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at Object.base64ToArrayBuffer ([REDACTED]/resources/app.asar/preload.bundle.js:2:4315493)
    at Object.encryptProfileData ([REDACTED]/resources/app.asar/preload.bundle.js:2:7165507)
    at Object.writeProfile ([REDACTED]/resources/app.asar/preload.bundle.js:2:6464336)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:6652270
```
This suggests that my profile key is undefined in Signal Desktop.
Signal Desktop does not know my profile name, too.

**Comment by Blackoverflow** [comment]
This one works for me since Axolotl 1.0.6 or so. I'll close it. If someone still experiences it, he/she/* can open this issue again.

**Comment by mdehollander** [comment]
I still have the same using Axolotl 1.08 and Signal Desktop 5.32.1 (snap). Relevant snippet from the logs:
```
INFO  2021-12-12T17:00:34.246Z Starting handleDataMessage for message [REDACTED]0c1.1 1639328433713 in conversation groupv2([REDACTED]xGQ=)
INFO  2021-12-12T17:00:34.247Z handleDataMessage: duplicate check db lookup needed [REDACTED]160.1-1639328433713
INFO  2021-12-12T17:00:34.247Z MessageReceiver.decryptAndCacheBatch fully processed
INFO  2021-12-12T17:00:34.250Z maybeFetchCredentials: no new credentials needed
INFO  2021-12-12T17:00:34.250Z getGroupUpdates/groupv2([REDACTED]xGQ=): Starting...
INFO  2021-12-12T17:00:34.251Z getGroupUpdates/groupv2([REDACTED]xGQ=): Processing just one change
INFO  2021-12-12T17:00:34.259Z integrateGroupChange/groupv2([REDACTED]xGQ=): Applying group change actions, from version 1 to 2
INFO  2021-12-12T17:00:34.260Z extractDiffs/groupv2([REDACTED]xGQ=) complete, generated 1 change messages
INFO  2021-12-12T17:00:34.265Z changedConvoBatcher: deduped 1 into 1
WARN  2021-12-12T17:00:34.285Z Received message destined for group groupv2([REDACTED]xGQ=), which we or the sender are not a part of. Dropping.
```
```
INFO  2021-12-12T18:39:30.405Z longRunningTaskWrapper/onAccept/groupv2([REDACTED]xGQ=): Starting task
INFO  2021-12-12T18:39:30.405Z enableProfileSharing: groupv2([REDACTED]xGQ=) storage? false
INFO  2021-12-12T18:39:30.406Z modifyGroupV2/promotePendingMember/groupv2([REDACTED]xGQ=): Starting attempt 0
INFO  2021-12-12T18:39:30.406Z waitForEmptyEventQueue: Waiting for event handler queue idle...
INFO  2021-12-12T18:39:30.406Z modifyGroupV2/promotePendingMember/groupv2([REDACTED]xGQ=): Queuing attempt 0
INFO  2021-12-12T18:39:30.407Z modifyGroupV2/promotePendingMember/groupv2([REDACTED]xGQ=): Running attempt 0
INFO  2021-12-12T18:39:30.408Z GET (WS) https://chat.signal.org/v1/profile/[REDACTED]8d1
INFO  2021-12-12T18:39:30.454Z NotificationService not updating notifications. Notifications are enabled; app is focused; there is no notification data
INFO  2021-12-12T18:39:30.507Z GET (WS) https://chat.signal.org/v1/profile/[REDACTED]8d1 200 Success
INFO  2021-12-12T18:39:30.507Z Setting sealedSender to UNRESTRICTED for conversation [REDACTED]8d1 ([REDACTED]b10)
INFO  2021-12-12T18:39:30.509Z Conversation job modifyGroupV2 took 103ms
ERROR 2021-12-12T18:39:30.509Z modifyGroupV2/promotePendingMember/groupv2([REDACTED]xGQ=): Error updating: Error: promotePendingMember/groupv2([REDACTED]xGQ=): No profileKeyCredential for conversation [REDACTED]8d1 ([REDACTED]b10)
    at ConversationModel.promotePendingMember ([REDACTED]/resources/app.asar/preload.bundle.js:2:5691096)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5486376
    at async run ([REDACTED]/resources/app.asar/preload.bundle.js:2:7344781)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:7344813
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5739865
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:3277068
ERROR 2021-12-12T18:39:30.510Z longRunningTaskWrapper/onAccept/groupv2([REDACTED]xGQ=): Error! Error: promotePendingMember/groupv2([REDACTED]xGQ=): No profileKeyCredential for conversation [REDACTED]8d1 ([REDACTED]b10)
    at ConversationModel.promotePendingMember ([REDACTED]/resources/app.asar/preload.bundle.js:2:5691096)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5486376
    at async run ([REDACTED]/resources/app.asar/preload.bundle.js:2:7344781)
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:7344813
    at async [REDACTED]/resources/app.asar/preload.bundle.js:2:5739865
```
