### ISSUE TITLE
[BUG] Axolotl crashes shortly after starting

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/axolotl#928]
### Description

Today, my Axolotl did not receive any messages and now, after restating the app, Axolotl crashes shortly after starting. 
This may be related to #926 

### Steps to Reproduce

I don't know how to reproduce this bug.

**Expected behavior:**
Axolotl starts and is able to receive and send messages

**Actual behavior:** 
At first, Axolotl was running, but not receiving messages. After restarting it, it crashes.

#### Versions

1.5.0 UT OpenStore Version
For testing, it was shortly on a build from 1.5.1 with updated dependency to[ signal-golang/textsecure commit ed24f00](https://github.com/signal-golang/textsecure/commit/ed24f002648dc08cff85ba22971c277f00dca104)

#### Device
Volla Phone running UT OTA-23

#### Debug Log
Log from before restarting:
```log
...
[36mINFO[0m[0031] [axolotl] Db setup finished                  
INFO[0000] [textsecure] Setting log level to error
[31mERRO[0m[2022/10/26 08:47:55] [textsecure] decrypt profile error nonceAndCipher too short 
[31mERRO[0m[2022/10/26 08:47:56] [textsecure] decrypt profile error nonceAndCipher too short 
[31mERRO[0m[2022/10/26 08:48:03] failed to handle message, signalingkey has wrong version, please re-register to update your signaling-key 
[31mERRO[0m[2022/10/26 08:48:04] [textsecure] Failed to handle received message  [31merror[0m="[textsecure] handleReceivedMessage content length is 0"
[31mERRO[0m[2022/10/26 08:48:04] failed to handle message, signalingkey has wrong version, please re-register to update your signaling-key 
[31mERRO[0m[2022/10/26 08:48:04] [textsecure-crayfish-ws] Failed to send websocket message  [31merror[0m="write tcp 127.0.0.1:60110->127.0.0.1:9081: use of closed network connection"
[31mERRO[0m[2022/10/26 08:48:04] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="websocket: close 1006 (abnormal closure): unexpected EOF"
[31mERRO[0m[2022/10/26 08:48:04] [textsecure-crayfish] Starting crayfish-backend c.cmd.Wait() failed with 'exit status 101' 
---
[31mERRO[0m[2022/10/26 08:48:06] dial tcp [::1]:9081: connect: connection refused 
[31mERRO[0m[2022/10/26 08:48:06] [textsecure-crayfish-ws] Failed to start listening  [31merror[0m="dial tcp [::1]:9081: connect: connection refused"
--- last two lines repeated for ~ 10 hours
```
Log from after restart (and each trial to start Axolotl since then)
```log
...
[36mINFO[0m[0036] [axolotl] Db setup finished                  
INFO[0000] [textsecure] Setting log level to error
[31mERRO[0m[2022/10/26 18:23:18] [textsecure] decrypt profile error nonceAndCipher too short 
[31mERRO[0m[2022/10/26 18:23:19] [textsecure] decrypt profile error nonceAndCipher too short 
[31mERRO[0m[2022/10/26 18:23:23] failed to handle message, signalingkey has wrong version, please re-register to update your signaling-key 
panic: runtime error: makeslice: len out of range

goroutine 34 [running]:
github.com/nanu-c/zkgroup.ClientZkGroupCipher.DecryptBlob(0x4003768640, 0x121, 0x121, 0x0, 0x0, 0x0, 0x0, 0x0, 0x31, 0x200, ...)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/nanu-c/zkgroup@v0.9.0/client.go:45 +0x40
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).decryptGroup(0x40071ccda0, 0x75c7ac9108, 0x18, 0x40054726f0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/groupsv2/decrypt.go:43 +0x1f0
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).decryptGroupFromServer(0x4005a25b00, 0x4005453cc0, 0x0, 0x0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/groupsv2/decrypt.go:17 +0x8c
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).UpdateGroupFromServer(0x4005a25b00, 0x40, 0x0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/groupsv2/groupsv2.go:215 +0x144
github.com/signal-golang/textsecure/groupsv2.HandleGroupsV2(0x0, 0x0, 0x40000ec5a0, 0x4, 0x4, 0x0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/groupsv2/groupsv2.go:250 +0x254
github.com/signal-golang/textsecure.handleDataMessage(0x0, 0x0, 0x40021ff5c0, 0x24, 0x18400878d21, 0x40000ec5a0, 0x0, 0x4878e0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/handler.go:87 +0x18c
github.com/signal-golang/textsecure.handleMessage(0x0, 0x0, 0x40021ff5c0, 0x24, 0x18400878d21, 0x4005978380, 0x31, 0x33, 0x2fd, 0x0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/handler.go:22 +0x444
github.com/signal-golang/textsecure.handleReceivedMessage(0x40036b1200, 0x2fd, 0x300)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/textsecure.go:652 +0xd18
github.com/signal-golang/textsecure.StartListening(0x0, 0x0)
	/github/workspace/$GITHUB_WORKSPACE/go/pkg/mod/github.com/signal-golang/textsecure@v1.13.0/websocket.go:199 +0x5d4
github.com/nanu-c/axolotl/app/worker.RunBackend()
	/github/workspace/app/worker/textsecureapi.go:170 +0x36c
created by main.runBackend
	/github/workspace/main.go:39 +0x30

```

**Comment by rubdos** [comment]
FYI https://github.com/whisperfish/libsignal-service-rs/pull/168

We should've seen this coming, but alas. Should be an easy fix, however.

**Comment by rubdos** [comment]
> �[31mERRO�[0m[2022/10/26 18:23:23] failed to handle message, signalingkey has wrong version, please re-register to update your signaling-key 

This doesn't look like a TLS error, but it's suspicious in timing. Leaving https://github.com/whisperfish/libsignal-service-rs/pull/168 here.
