### ISSUE TITLE
[BUG] Existing chats disappear after updating to v1.6.0

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#933]
### Description
After updating to v1.6.0 the chat list is empty and only after receiving a new message, old chats are reappearing with old messages inside.
Creating a new chat results in an empty chat without historic messages.

### Steps to Reproduce
1. Update to v1.6.0
2. Open Axolotl
3. Chat list is empty

**Expected behavior:**
Existing chats stay in chat list after update.

**Actual behavior:**
Chat list is empty.

#### Versions
v1.6.0

#### Device
Mobian@Pinephone

#### Link to Debug Log
No logs

**Comment by tsiksum** [comment]
Different on FP3. All the messages I had before updating showed. After updating some of the missing messages trickling in with every restart.

**Comment by Blackoverflow** [comment]
For me, only some chats remained after updating. But when I started a new chat, it contained the message history of another chat. I don't know yet who would get a message I would write now.

**Comment by Blackoverflow** [comment]
Did Axolotl crash at the first start up after updating to Version 1.6.0?
@tsiksum do you have group chats that did not vanish after updating?

**Comment by Blackoverflow** [comment]
This crash log may be the reason:
```log
[36mINFO[0m[2022/10/28 22:33:01] [axolotl][update v_1_6_0] migrate groupv2 session 
[36mINFO[0m[2022/10/28 22:33:02] [axolotl][update v_1_6_0] migrate groupv2 session: members 
[37mDEBU[0m[2022/10/28 22:33:02] [textsecure][groupsv2] update group from server 
[37mDEBU[0m[2022/10/28 22:33:02] [textsecure][groupsv2] queryGroupChangeFromServer 
[37mDEBU[0m[2022/10/28 22:33:02] [textsecure][groupsv2] get groupCredentials  
[37mDEBU[0m[2022/10/28 22:33:02] [textsecure-crayfish-ws] websocket Connected successfully 
[37mDEBU[0m[2022/10/28 22:33:02] [crayfish] establishing client connection... WebSocket 
[36mINFO[0m[2022/10/28 22:33:02] [axolotl-qml] qml: [Axolotl Web View] [JS] (http://localhost:9080/assets/index.41bdc0c0.js: 19) No translations found for en-GB 
[36mINFO[0m[2022/10/28 22:33:02] [axolotl-qml] qml: [Axolotl Web View] [JS] (http://localhost:9080/assets/index.41bdc0c0.js: 19) No translations found for en-GB 
[36mINFO[0m[2022/10/28 22:33:02] [axolotl-qml] qml: [Axolotl Web View] [JS] (http://localhost:9080/assets/index.41bdc0c0.js: 19) No translations found for en-GB 
[37mDEBU[0m[2022/10/28 22:33:03] [textsecure] GET /v1/certificate/group/19293/19300 200 
[37mDEBU[0m[2022/10/28 22:33:03] [textsecure] GET with auth /v1/groups/ 401   
[37mDEBU[0m[2022/10/28 22:33:03] [textsecure][groupsv2] queryGroupChangeFromServer group 
[37mDEBU[0m[2022/10/28 22:33:03] [textsecure][groupsv2] decrypt group         
panic: runtime error: makeslice: len out of range

goroutine 5 [running]:
github.com/nanu-c/zkgroup.ClientZkGroupCipher.DecryptBlob(0x40050b83c0, 0x121, 0x121, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40001360a0, 0x4005069110, ...)
	/gopath/path0/pkg/mod/github.com/nanu-c/zkgroup@v0.9.0/client.go:45 +0x40
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).decryptGroup(0x400054b9f0, 0x73f540, 0x40001800c0, 0x4000600e00)
	/gopath/path0/pkg/mod/github.com/!blackoverflow/textsecure@v1.4.3-0.20221028183342-5dd575a18460/groupsv2/decrypt.go:43 +0x1f0
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).decryptGroupFromServer(0x40005b3e00, 0x4005206640, 0x0, 0x0)
	/gopath/path0/pkg/mod/github.com/!blackoverflow/textsecure@v1.4.3-0.20221028183342-5dd575a18460/groupsv2/decrypt.go:17 +0x8c
github.com/signal-golang/textsecure/groupsv2.(*GroupV2).UpdateGroupFromServer(0x40005b3e00, 0x40, 0x40005b3e00)
	/gopath/path0/pkg/mod/github.com/!blackoverflow/textsecure@v1.4.3-0.20221028183342-5dd575a18460/groupsv2/groupsv2.go:215 +0x144
github.com/signal-golang/textsecure/groupsv2.GetGroupV2MembersForGroup(0x4001034440, 0x40, 0x400054bcc8, 0x1, 0x1, 0x0, 0x0)
	/gopath/path0/pkg/mod/github.com/!blackoverflow/textsecure@v1.4.3-0.20221028183342-5dd575a18460/groupsv2/groupsv2.go:232 +0x44
github.com/signal-golang/textsecure.GetGroupV2MembersForGroup(...)
	/gopath/path0/pkg/mod/github.com/!blackoverflow/textsecure@v1.4.3-0.20221028183342-5dd575a18460/server.go:401
github.com/nanu-c/axolotl/app/store.sessionV1ToGroupV2(0x40032ac0b0, 0x0, 0x0)
	/home/blackoverflow/Softwareprojekte/axolotl/app/store/migrations.go:159 +0x304
github.com/nanu-c/axolotl/app/store.sessionsV1toSessionsV2(0x4000180080, 0x4)
	/home/blackoverflow/Softwareprojekte/axolotl/app/store/migrations.go:228 +0x134
github.com/nanu-c/axolotl/app/store.Migrate(0x4000336c80, 0x0)
	/home/blackoverflow/Softwareprojekte/axolotl/app/store/db.go:310 +0x80
github.com/nanu-c/axolotl/app/worker.startSession()
	/home/blackoverflow/Softwareprojekte/axolotl/app/worker/textsecureapi.go:215 +0x190
github.com/nanu-c/axolotl/app/worker.RunBackend(0x4000480000, 0x0, 0x0)
	/home/blackoverflow/Softwareprojekte/axolotl/app/worker/textsecureapi.go:180 +0x510
created by main.runBackend
	/home/blackoverflow/Softwareprojekte/axolotl/main.go:40 +0x50
```
Did someone have similar log lines?

**Comment by tsiksum** [comment]
> Did Axolotl crash at the first start up after updating to Version 1.6.0? @tsiksum do you have group chats that did not vanish after updating?

None of my group chats vanished aufter update. They were incomplete before update and (some of) the missing messages trickled in after update and restarting Ax al zillion times. But not all of them up to now.

**Comment by tsiksum** [comment]
> This crash log may be the reason:
> [...] 
> Did someone have similar log lines?

I did not encounter any crash after update. Therefore no "panic" to be found in the logs.
